import asyncio
import os
import sys
import json
from langchain_mcp_adapters.client import MultiServerMCPClient
from langchain_core.prompts import ChatPromptTemplate
from dotenv import load_dotenv
load_dotenv(override=True)
from langgraph.graph import StateGraph, START, END
from langgraph.types import Send
from pathlib import Path
from context import QUERY_GUARDRAILS_CONTEXT, QUERY_SYSTEM_PROMPT
from config import COLLECTION1

from config import MODEL_ID
from models import RouterDecision, WorkerState, MasterState, AgentState, TaskState
from utils import execute_mongo_query, llm
import dependencies # this statement is required
from dependencies import logger
from utils import startup_db_client, get_unique_names_from_database
from rag_ingestion import initialize_chromadb


# Configure the endpoint for your HTTP SSE MCP Server
MCP_SERVER_SSE_URL = "http://127.0.0.1:8090/sse"

async def _bootstrap_runtime():
    db = await startup_db_client()
    chroma_collection = initialize_chromadb()
    return chroma_collection, {}

structured_router = llm.with_structured_output(RouterDecision)

# ==========================================
# UPDATED BUILD ORCHESTRATOR (USING SSE API)
# ==========================================
async def build_orchestrator():
    chroma_collection, UNIQUE_NAMES_DICT = await _bootstrap_runtime()
    
    # ---------------------------------------------------------------
    # CHANGED: Replaced stdio command config with SSE HTTP Endpoint API
    # ---------------------------------------------------------------
    mcp_client = MultiServerMCPClient({
        "mcp_web_tools": {
            "url": MCP_SERVER_SSE_URL,
            "transport": "sse"
        }
    })

    # Load MCP Tools dynamically via the HTTP/SSE connection
    tools_list = await mcp_client.get_tools()
    mcp_tools = {tool.name: tool for tool in tools_list}
    
    # Fetch HTTP API Tools exposed by FastMCP
    mcp_find_tables = mcp_tools.get("find_relevant_tables")
    mcp_exec_read = mcp_tools.get("execute_read_query")

    # ==========================================
    # Graph Nodes Calling MCP Tools via API
    # ==========================================

    async def rag_worker(state: AgentState):
        """RAG retriever node enhanced with MCP schema lookup API."""
        logger.info(f"rag_worker_node called")
        
        # Call RAG tool exposed over MCP SSE API
        if mcp_find_tables:
            rag_schema_info = await mcp_find_tables.ainvoke({"user_intent": state.get("user_prompt")})
            logger.info(f"MCP API Schema Result: {rag_schema_info}")

        results = chroma_collection.query(query_texts=[state.get("user_prompt")], n_results=min(2, chroma_collection.count()))
        if not results or not results["metadatas"]:
            return "No matching database schemas located for this intent."
        
        return {"retrieved_docs": results["metadatas"]}

    def supervisor_fanout(state: AgentState):
        """Supervisor router: Dynamic parallel fan-out using Send()."""
        logger.info(f"supervisor_fanout called")
        fanout_branches = []
        for doc in state["retrieved_docs"][0]:
            logger.info(f'{doc=}')
            fanout_branches.append(
                Send("generate_mongodb_query_node", {
                    "doc": doc, 
                    "user_prompt": state["user_prompt"]
                })
            )
        return fanout_branches

    async def generate_mongodb_query_node(state: TaskState):
        """Node formulating target queries."""
        logger.info(f"generate_mongodb_query_node called")
        doc = state.get("doc", {})
        logger.info(f"retrieved_doc: {json.dumps(doc, indent=4)}")

        query_system_prompt = QUERY_SYSTEM_PROMPT.format(
            QUERY_GUARDRAILS_CONTEXT=QUERY_GUARDRAILS_CONTEXT,
            CONTEXT=doc.get("schema", "").format(COLLECTION1=COLLECTION1),
        )
        
        # Example query string generated by model logic
        query = f"db.{doc.get('target', 'collection')}.find({{}})"
        
        return {"mongodb_queries": [query]}

    async def execute_mongodb_query_node(state: AgentState):
        """Executes read operations against the database via the MCP API."""
        logger.info(f"execute_mongodb_query_node called")
        results = []
        
        for q in state.get("mongodb_queries", []):
            if mcp_exec_read:
                # Call execute_read_query API tool endpoint
                res = await mcp_exec_read.ainvoke({"query_string": "SELECT * FROM financial_metrics;"})
                results.append(res)
                
        return {"query_results": results}

    # ==========================================
    # Graph Construction
    # ==========================================
    builder = StateGraph(AgentState)

    builder.add_node("rag_worker", rag_worker)
    builder.add_node("generate_mongodb_query_node", generate_mongodb_query_node)
    builder.add_node("execute_mongodb_query_node", execute_mongodb_query_node)

    # Graph Connections
    builder.add_edge(START, "rag_worker")

    builder.add_conditional_edges(
        "rag_worker",
        supervisor_fanout,
        ["generate_mongodb_query_node"]
    )

    builder.add_edge("generate_mongodb_query_node", "execute_mongodb_query_node")
    builder.add_edge("execute_mongodb_query_node", END)

    return builder.compile()

async def run_pipeline():
    cross_db_query = "can u tell me the revenue for financial metrics"

    initial_state = {
        "user_prompt": cross_db_query,
        "retrieved_docs": [],
        "mongodb_queries": [],
        "query_results": [],
        "final_response": ""
    }

    graph = await build_orchestrator()
    final_state = await graph.ainvoke(initial_state)
    logger.info(f"Pipeline Result: {final_state}")

if __name__ == "__main__":
    asyncio.run(run_pipeline())